export const columns = [
  {
    name: 'Experimental',
    selector: 'theoretical',
    omit: true,
    format: 'BOOLEAN_CLASS',
    formatArg: 'fa fa-asterisk',
  },
  {
    name: 'Material ID',
    selector: 'task_id',
    format: 'LINK',
    formatArg: '/materials/',
    minWidth: '130px',
  },
  {
    name: 'Formula',
    selector: 'formula_pretty',
    format: 'FORMULA',
    minWidth: '130px',
  },
  {
    name: 'Crystal System',
    selector: 'symmetry.crystal_system',
  },
  {
    name: 'Space Group Symbol',
    selector: 'symmetry.symbol',
    format: 'SPACEGROUP_SYMBOL',
  },
  {
    name: 'Space Group Number',
    selector: 'symmetry.number',
    right: true,
  },
  {
    name: 'Volume',
    selector: 'volume',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: '\u00c5\u00b3',
    omit: true,
    right: true,
  },
  {
    name: 'Density',
    selector: 'density',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'cm\u00b3',
    omit: true,
    right: true,
  },
  {
    name: 'Sites',
    selector: 'nsites',
    right: true,
  },
  {
    name: 'Energy Above Hull',
    selector: 'e_above_hull',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'meV/atom',
    conversionFactor: 1000,
    abbreviateNearZero: true,
    right: true,
  },
  {
    name: 'Formation Energy',
    selector: 'formation_energy_per_atom',
    format: 'SIGNIFICANT_FIGURES',
    formatArg: 3,
    units: 'eV/atom',
    omit: true,
    right: true,
  },
  {
    name: 'Predicted Stable',
    selector: 'is_stable',
    format: 'BOOLEAN',
    formatArg: ['yes', 'no'],
    omit: true,
    right: false,
  },
  {
    name: 'Magnetic Ordering',
    selector: 'ordering',
    omit: true,
  },
  {
    name: 'Max Magnetic Moment',
    selector: 'total_magnetization',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
  },
  {
    name: 'Bulk Modulus, Voigt',
    selector: 'k_voigt',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Bulk Modulus, Reuss',
    selector: 'k_reuss',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Bulk Modulus, VRH',
    selector: 'k_vrh',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Shear Modulus, Voigt',
    selector: 'g_voigt',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Shear Modulus, Reuss',
    selector: 'g_reuss',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Shear Modulus, VRH',
    selector: 'g_vrh',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'GPa',
    omit: true,
    right: true,
  },
  {
    name: 'Elastic Anisotropy',
    selector: 'universal_anisotropy',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Weighted Surface Energy',
    selector: 'weighted_surface_energy',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'J/m\u00b2',
    omit: true,
    right: true,
  },
  {
    name: 'Surface Anisotropy',
    selector: 'surface_anisotropy',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Shape Factor',
    selector: 'shape_factor',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Work Function',
    selector: 'weighted_work_function',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Piezoelectric Modulus',
    selector: 'e_ij_max',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    units: 'C/m\u00b2',
    omit: true,
    right: true,
  },
  {
    name: 'Total Dielectric Constant',
    selector: 'e_total',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Ionic Dielectric Constant',
    selector: 'e_ionic',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
  {
    name: 'Static Dielectric Constant',
    selector: 'e_static',
    format: 'FIXED_DECIMAL',
    formatArg: 2,
    omit: true,
    right: true,
  },
];
